name: 📄 Extract version

on:
  workflow_call:
    outputs:
      result:
        description: Version name extracted, sanitized and slugified (e.g. 'main', 'develop', '1.2.3').
        value: ${{ jobs.extract-version.outputs.result }}

permissions:
  contents: read

jobs:
  extract-version:
    name: Extract version

    runs-on: ubuntu-latest

    steps:
      - name: 📄 Extract version
        id: extract-version
        uses: anthonypillot/actions/.github/actions/extract-version@v1

    outputs:
      result: ${{ steps.extract-version.outputs.result }}
